FROM ruby:3.4.2

WORKDIR /app

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  default-mysql-client \
  curl \
  yarn \
  nodejs \
  && rm -rf /var/lib/apt/lists/*

RUN gem install bundler -v 2.6.6

COPY Gemfile Gemfile.lock ./
RUN bundle install --without development test

COPY . .

CMD ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -e production"]
